// GENERATED by tools/extract-engine.py from index.html — do not edit by hand while
// index.html still carries its own copy. Once index.html imports this module, delete
// the generator and maintain this file directly.
//
// The bodies below are byte-identical to the in-page originals. Only the surrounding
// scope changed: the engine's former globals are now closure variables, so the same
// simulation can run in a browser, in Node, from a CLI, or under test.

const SEEDED_PHASES = [
  {id:'repair-buf', label:'Repair buffer (savings)',cost:1000,isSavings:true},
  {id:'jon-tires',  label:"Jon's tires + oil",    cost:1500},
  {id:'karen-tires',label:"Karen's tires",         cost:1000},
  {id:'dental',     label:'Dental — Jon + Karen',  cost:600},
  {id:'glasses',    label:'Glasses — Jon + Karen', cost:1000},
];

export const DEFAULT_PHASES = SEEDED_PHASES;

export const MN = ['January','February','March','April','May','June','July','August','September','October','November','December'];
export const DN = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];

/**
 * @param {object}  opts.state          the Firebase `S` state object
 * @param {Date|string} [opts.now]      "today" for the simulation (default: real now)
 * @param {Array}  [opts.defaultPhases] override the seeded phase list
 */
export function createEngine(opts = {}) {
  const S = opts.state || {};
  const now = opts.now ? new Date(opts.now) : new Date();
  const mKey = `${now.getFullYear()}-${now.getMonth()}`;
  // must be named DEFAULT_PHASES: the verbatim bodies below reference that identifier
  const DEFAULT_PHASES = opts.defaultPhases || SEEDED_PHASES;
  const DEFAULT_USER_BILLS = [];
  let _cachedRoadmap = null, _roadmapCacheKey = '';

  function getPhases() {
    return (S && S.phases && S.phases.length > 0) ? S.phases : DEFAULT_PHASES;
  }

  function isoDay(d) {
    return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  }

  function bal(cb, id) {
    // First check S.cardBals, then S.cardStartBals from Firebase
    if (cb && cb[id] !== undefined) return cb[id];
    if (S.cardStartBals && S.cardStartBals[id] !== undefined) return S.cardStartBals[id];
    return 0;
  }

  function jonPaidThisPeriod(year, month, schedDay) {
    const lpd = S.jonLastPayDate;
    if (!lpd) return false;
    const lp = new Date(lpd + 'T12:00:00');
    const ly = lp.getFullYear(), lm = lp.getMonth(), ld = lp.getDate();
    if (schedDay === 7) {
      const pm = month === 0 ? 11 : month - 1, py = month === 0 ? year - 1 : year;
      return (ly === py && lm === pm && ld >= 23) || (ly === year && lm === month && ld < 7);
    }
    return ly === year && lm === month && ld >= 8 && ld < 22;
  }

  function isKarenPayday(year, month, day) {
    const anchor = S.karenLastPayDate;
    if (!anchor) return new Date(year, month, day).getDay() === 4; // fallback: every Thursday
    const anchorMs = new Date(anchor + 'T12:00:00').getTime();
    const thisMs   = new Date(year, month, day).getTime();
    const diff     = Math.round((thisMs - anchorMs) / 86400000);
    return diff % 7 === 0;
  }

  function getDailyBills(year, month, day, cardBalOverride) {
    const bills = [];
    const key = `${year}-${String(month + 1).padStart(2, '0')}`;
    const dow = new Date(year, month, day).getDay();
    const cb = cardBalOverride || (S.cardBals || {});
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const thisDate = new Date(year, month, day);
    const isFuture = thisDate > today;

    // Income
    let currentKaren = isFuture ? (S.karenAvgPay || S.karenLastPay || 810) : (S.karenLastPay || 810);
    let currentJon = isFuture ? (S.jonAvgPay || S.jonLastPay || 1641) : (S.jonLastPay || 1641);
    if (isFuture) { currentKaren = Math.floor(currentKaren); currentJon = Math.floor(currentJon); }

    if (day === 7 && !jonPaidThisPeriod(year,month,7)) bills.push({ label: 'Jon paycheck', amt: currentJon, isIncome: true });
    if (day === 22 && !jonPaidThisPeriod(year,month,22)) bills.push({ label: 'Jon paycheck', amt: currentJon, isIncome: true });
    // Show on actual paydate if it landed off-schedule
    const _jlpd=S.jonLastPayDate;
    if(_jlpd){const _jlp=new Date(_jlpd+'T12:00:00');if(_jlp.getFullYear()===year&&_jlp.getMonth()===month&&_jlp.getDate()===day&&day!==7&&day!==22)bills.push({label:'Jon paycheck',amt:currentJon,isIncome:true});}
    if (isKarenPayday(year, month, day)) bills.push({ label: 'Karen paycheck', amt: currentKaren, isIncome: true });

    // Process all userBills from Firebase
    const userBills = S.userBills || [];
  
    userBills.forEach(b => {
      // Check conditionEnd (e.g., "2027-03" — skip if past end date)
      if (b.conditionEnd && key > b.conditionEnd) return;
      // Bills with day 0 and no frequency are tracked via dedicated sync functions
      if (b.day === 0 && !b.frequency) return;
      // Self-liquidating bills (endDate set, no cardId) — stop after end month
      if (!b.cardId && b.endDate && key > b.endDate) return;
      // Skip paid-off snowball targets (cardId with balance at zero)
      if (b.cardId && bal(cb, b.cardId) <= 0) return;
    
      // Determine if this bill falls on this day
      let matchesDay = false;
    
      if (b.frequency === 'weekly' && b.dow !== undefined) {
        matchesDay = (dow === b.dow);
      } else if (b.frequency === 'quarterly' && b.frequencyMonths) {
        matchesDay = (day === b.day && b.frequencyMonths.includes(month));
      } else if (Array.isArray(b.day)) {
        matchesDay = b.day.map(Number).includes(day);
      } else {
        // Clamp to the last day of the month for bills whose day (e.g. 30 or 31)
        // doesn't exist in shorter months (Feb, Apr, Jun, Sep, Nov) instead of
        // silently skipping the bill that month
        const dimForBill = new Date(year, month + 1, 0).getDate();
        const effectiveDay = Math.min(b.day, dimForBill);
        matchesDay = (day === effectiveDay);
      }
    
      if (matchesDay && b.amt && b.amt !== 0) {
        bills.push({
          label: b.name,
          amt: -Math.abs(b.amt),
          isIncome: false,
          billId: b.id,
          ...(b.cardId ? { cardId: b.cardId } : {})
        });
      }
    });

    // Discretionary (Sunday)
    if (dow === 0) {
      const weeklyAmt = S.discWeekly || 50;
      const monthlyCap = S.discMonthlyCap || 200;
      const isCurrentMonth = year === now.getFullYear() && month === now.getMonth();
      const actualSpent = isCurrentMonth ? (S.discSpent || 0) : 0;
      let plannedSpent = 0;
      for (let i = 1; i < day; i++) {
        if (new Date(year, month, i).getDay() === 0) plannedSpent += weeklyAmt;
      }
      const totalSpent = Math.max(actualSpent, plannedSpent);
      if (totalSpent < monthlyCap) {
        const lastDay = new Date(year, month + 1, 0).getDate();
        const isLastSunday = (day + 7) > lastDay;
        const remaining = monthlyCap - totalSpent;
        bills.push({
          label: 'Discretionary',
          amt: isLastSunday ? -remaining : -Math.min(weeklyAmt, remaining),
          isIncome: false
        });
      }
    }

    return bills.filter(b => b.amt !== 0);
  }

  const phaseAmt=(id,def)=>{if(S.phaseCosts&&S.phaseCosts[id]!==undefined)return S.phaseCosts[id];return def;};

  function getSnowballTargets() {
    // Build snowball targets from userBills that have a cardId
    const seen = new Set();
    const targets = [];
    (S.userBills || []).forEach(b => {
      if (b.cardId && !seen.has(b.cardId)) {
        seen.add(b.cardId);
        targets.push({
          id: b.cardId,
          label: b.name,
          startBal: bal(S.cardBals || {}, b.cardId),
          minPay: b.amt || 0
        });
      }
    });
    return targets;
  }

  function calcRoadmap(){
    const phasesKey = JSON.stringify(getPhases());
    const phaseDoneKey = JSON.stringify(S.phaseDone || {});
    const cardBalsKey = JSON.stringify(S.cardBals || {});
    const userBillsKey = JSON.stringify((S.userBills || []).filter(b => b.cardId || b.endDate).map(b => b.id));
    const cacheKey = `${S.bal4496}-${S.karenLastPay||0}-${S.karenAvgPay||0}-${S.karenLastPayDate||''}-${phasesKey}-${phaseDoneKey}-${cardBalsKey}-${userBillsKey}`;
  
    if (_cachedRoadmap && _roadmapCacheKey === cacheKey) {
      return _cachedRoadmap;
    }
  
    let balance=S.bal4496||0;
    const origCB=S.cardBals;
    const milestones={};
    const balLog={};
    const sinkingLog={};
    const phaseDone=S.phaseDone||{};
    const sinkingSaves={};

    const TARGETS = getSnowballTargets();

    // Clone card balances for simulation
    const cardBals={};
    TARGETS.forEach(t=>{cardBals[t.id]=bal(S.cardBals||{},t.id);});

    // Pending expense phases — split into threshold (blocks snowball) and sinking (runs concurrently)
    const allPending=getPhases().filter(p=>!phaseDone[p.id]);
    const pendingThresholdPhases=allPending.filter(p=>!p.monthlySave&&!p.percentOfPay);
    const pendingSinkingPhases=allPending.filter(p=>p.monthlySave||p.percentOfPay);
    pendingSinkingPhases.forEach(p=>{sinkingSaves[p.id]=0;});
    let lastPhaseDate=null;
    let snowballActive=pendingThresholdPhases.length===0;
    let snowIdx=TARGETS.findIndex(t=>cardBals[t.id]>0);
    if(snowIdx===-1)snowIdx=null;

    // Pre-check: if today's actual balance already covers the next phase, lock it to today
    // Built from local date components (not toISOString, which shifts to UTC and can land on
    // the wrong calendar day in the evening for US timezones behind UTC)
    const todayStr=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;
    if(pendingThresholdPhases.length>0){
      const phase=pendingThresholdPhases[0];
      const needed=phaseAmt(phase.id,phase.cost)+800;
      if(balance>=needed){
        milestones[phase.id]={date:todayStr,bal:Math.round(balance)};
        balance-=phaseAmt(phase.id,phase.cost);
        lastPhaseDate=new Date(now);
        pendingThresholdPhases.shift();
        if(pendingThresholdPhases.length===0){
          snowballActive=true;
          milestones['snowball-start']={date:todayStr};
        }
      }
    }
    if(snowballActive && !milestones['snowball-start']){
      milestones['snowball-start']={date:todayStr};
    }

    // Store today's actual balance in balLog — it already reflects today's activity.
    // The simulation starts from tomorrow (line below), so no need to deduct today's bills.
    try{
      balLog[todayStr]=Math.round(balance);
    }finally{S.cardBals=origCB;}

    // Start simulation from tomorrow
    const d=new Date(now.getFullYear(),now.getMonth(),now.getDate()+1);

    for(let i=0;i<1500;i++){
      const yr=d.getFullYear(),mo=d.getMonth(),dy=d.getDate();
      const dateStr=isoDay(d);

      let dayBills;
      try{S.cardBals=cardBals;dayBills=getDailyBills(yr,mo,dy,cardBals);}finally{S.cardBals=origCB;}

      dayBills.forEach(b=>{
        balance+=b.amt;
        if(b.cardId&&cardBals[b.cardId]!==undefined){
          cardBals[b.cardId]=Math.max(0,cardBals[b.cardId]+b.amt);
        }
      });

      // Detect any target fully retired by its own minimum payment — not just the
      // currently active one. A smaller debt further down the queue can zero out on
      // its own before its turn arrives, since minimum payments run regardless of snowIdx.
      TARGETS.forEach(tgt=>{
        if(cardBals[tgt.id]<=0&&!milestones[tgt.id+'-done']){
          cardBals[tgt.id]=0;
          milestones[tgt.id+'-done']={date:dateStr,label:tgt.label};
        }
      });
      if(snowIdx!==null){
        while(snowIdx<TARGETS.length&&cardBals[TARGETS[snowIdx].id]<=0)snowIdx++;
        if(snowIdx>=TARGETS.length){
          if(!milestones['debt-free'])milestones['debt-free']={date:dateStr};
          snowIdx=null;
        }
      }

      // Check expense phase affordability (threshold-based only — sinking phases handled below)
      if(!snowballActive&&pendingThresholdPhases.length>0){
        const phase=pendingThresholdPhases[0];
        if(!phase.monthlySave){
          const gap=lastPhaseDate?Math.floor((d-lastPhaseDate)/86400000):999;
          if(!milestones[phase.id]&&gap>=14){
            const needed=phaseAmt(phase.id,phase.cost)+800;
            if(balance>=needed){
              const afterCost=balance-phaseAmt(phase.id,phase.cost);
              const nextJonDay=dy<7?7:dy<22?22:7;
              const nextJonMo=dy>=22?mo+1:mo;
              let sim=afterCost;
              let simOk=true;
              let rd=new Date(yr,mo,dy+1);
              const nextJon=new Date(yr,nextJonMo,nextJonDay);
              while(rd<nextJon){
                try{S.cardBals=cardBals;getDailyBills(rd.getFullYear(),rd.getMonth(),rd.getDate(),cardBals).forEach(b=>{sim+=b.amt;});}finally{S.cardBals=origCB;}
                if(sim<0){simOk=false;break;}
                rd.setDate(rd.getDate()+1);
              }
              if(simOk){
                milestones[phase.id]={date:dateStr,bal:Math.round(balance)};
                balance-=phaseAmt(phase.id,phase.cost);
                lastPhaseDate=new Date(d);
                pendingThresholdPhases.shift();
                if(pendingThresholdPhases.length===0){
                  snowballActive=true;
                  milestones['snowball-start']={date:dateStr};
                }
                balLog[dateStr]=Math.round(balance);
                d.setDate(dy+1);continue;
              }
            }
          }
        }
      }

      // Snowball payments on paycheck days — runs before sinking to get first crack at surplus
      if(snowballActive&&snowIdx!==null&&(dy===7||dy===22||isKarenPayday(yr,mo,dy))){
        const target=TARGETS[snowIdx];
        let reserve=0;
        const nextJonDay=dy<7?7:dy<22?22:7;
        const nextJonMo=dy>=22?mo+1:mo;
        let rd=new Date(yr,mo,dy+1);
        const nextJon=new Date(yr,nextJonMo,nextJonDay);
        while(rd<nextJon){
          try{S.cardBals=cardBals;getDailyBills(rd.getFullYear(),rd.getMonth(),rd.getDate(),cardBals).forEach(b=>{if(!b.isIncome&&b.amt<0&&b.label!==target.label)reserve+=Math.abs(b.amt);});}finally{S.cardBals=origCB;}
          rd.setDate(rd.getDate()+1);
        }
        const available=Math.max(0,balance-reserve);
        if(available>0&&cardBals[target.id]>0){
          let payment=Math.min(cardBals[target.id],available);
          if(balance-payment<200)payment=Math.max(0,balance-200);
          cardBals[target.id]-=payment;
          balance-=payment;
          if(cardBals[target.id]<=0){
            cardBals[target.id]=0;
            milestones[target.id+'-done']={date:dateStr,label:target.label};
            snowIdx++;
            if(snowIdx>=TARGETS.length){milestones['debt-free']={date:dateStr};snowIdx=null;}
          }
        }
      }

      // Concurrent sinking fund: set aside savings after snowball gets first priority
      // Runs regardless of snowballActive — sinking saves from remaining surplus
      if(pendingSinkingPhases.length>0&&(dy===7||dy===22||isKarenPayday(yr,mo,dy))){
        const jonAmt=Math.round(S.jonAvgPay||S.jonLastPay||1641);
        const karenAmt=Math.round(S.karenAvgPay||S.karenLastPay||810);
        const monthlyInc=jonAmt*2+Math.round(karenAmt*4.33);
        const payAmt=isKarenPayday(yr,mo,dy)?karenAmt:jonAmt;
        for(let si=pendingSinkingPhases.length-1;si>=0;si--){
          const sp=pendingSinkingPhases[si];
          const needed=phaseAmt(sp.id,sp.cost);
          let saveAmt=0;
          if(sp.savingsMode==='percent'&&sp.percentOfPay){
            saveAmt=Math.round(payAmt*sp.percentOfPay/100);
          }else if(sp.monthlySave){
            const saveFraction=Math.min(1,sp.monthlySave/monthlyInc);
            saveAmt=Math.round(payAmt*saveFraction);
          }
          if(saveAmt<=0)continue;
          const accumulated=sinkingSaves[sp.id]||0;
          if(balance>=saveAmt+300&&accumulated<needed){
            balance-=saveAmt;
            sinkingSaves[sp.id]=accumulated+saveAmt;
            sinkingLog[dateStr]=sinkingLog[dateStr]||{};
            sinkingLog[dateStr][sp.id]=(sinkingLog[dateStr][sp.id]||0)+saveAmt;
          }
          if((sinkingSaves[sp.id]||0)>=needed){
            milestones[sp.id]={date:dateStr,bal:Math.round(balance+(sinkingSaves[sp.id]||0))};
            sinkingSaves[sp.id]=0;
            pendingSinkingPhases.splice(si,1);
            balLog[dateStr]=Math.round(balance);
          }
        }
      }

      balLog[dateStr]=Math.round(balance);
      d.setDate(dy+1);
    }

    S.cardBals=origCB;
    const result = {milestones,balLog,sinkingLog,finalCardBals:cardBals};
    _cachedRoadmap = result;
    _roadmapCacheKey = cacheKey;
    return result;
  }

  function getMonthEvents(year,month,roadmap,balLog,sinkingLog){
    const evts=[];
    const key=`${year}-${String(month+1).padStart(2,'0')}`;
    const dim=new Date(year,month+1,0).getDate();
    const fromDay = 1;
  
    const phaseDone=S.phaseDone||{};
    // A target's "-done" milestone can land on any day within a month — comparing by
    // month alone (as this used to) treats a debt as already cleared for the ENTIRE
    // month it pays off in, even on days before its real payoff date. Compare exact
    // dates instead, computed fresh for whichever day is being evaluated.
    const cbAsOf=(dateStr)=>{
      const c={...(S.cardBals||{})};
      getSnowballTargets().forEach(t=>{
        const done=roadmap[t.id+'-done'];
        if(done&&done.date<=dateStr)c[t.id]=0;
      });
      return c;
    };
    const add=(day,title,amt,color,note='',isIncome=false,feat=false,isFinal=false,billId=null)=>{
      if(day>=1&&day<=dim)evts.push({day,title,amt,color,note,isIncome,feat,isFinal,billId});
    };

    const todayDate = new Date();
    todayDate.setHours(0,0,0,0);
    const checkFuture = (d) => new Date(year, month, d) > todayDate;

    function getSmartNote(m, y) {
      const currentGoalIndex = getPhases().findIndex(p => !(S.phaseDone && S.phaseDone[p.id]));
      if (currentGoalIndex === -1) return '→ Surplus to snowball target';
      const p = getPhases()[currentGoalIndex];
      if (y < now.getFullYear() || (y === now.getFullYear() && m < now.getMonth())) {
        return 'Paycheck'; 
      }
      return `→ Saving for ${p.label} ($${p.cost.toLocaleString()})`;
    }

    const pcNote = getSmartNote(month, year);

    // Paychecks
    if(7>=fromDay && !jonPaidThisPeriod(year,month,7)){
      let amt=checkFuture(7)?(S.jonAvgPay||S.jonLastPay||1641):(S.jonLastPay||1641);
      add(7,'Jon paycheck',amt,'#7aad4e',pcNote,true);
    }
    if(22>=fromDay && !jonPaidThisPeriod(year,month,22)){
      let amt=checkFuture(22)?(S.jonAvgPay||S.jonLastPay||1641):(S.jonLastPay||1641);
      add(22,'Jon paycheck',amt,'#7aad4e',pcNote,true);
    }
    // Show on actual paydate if it arrived off-schedule this month
    {const _jlpd=S.jonLastPayDate;if(_jlpd){const _jlp=new Date(_jlpd+'T12:00:00');if(_jlp.getFullYear()===year&&_jlp.getMonth()===month){const _jd=_jlp.getDate();if(_jd!==7&&_jd!==22&&_jd>=fromDay&&(jonPaidThisPeriod(year,month,7)||jonPaidThisPeriod(year,month,22))){add(_jd,'Jon paycheck',S.jonLastPay||1641,'#7aad4e',pcNote,true);}}}}

    for(let d=fromDay; d<=dim; d++) {
      if(isKarenPayday(year,month,d)) {
        let amt = checkFuture(d) ? (S.karenAvgPay || S.karenLastPay || 810) : (S.karenLastPay || 810);
        add(d, 'Karen paycheck — Copans', amt, '#7aad4e', 'Direct deposit to #4496', true);
      }
    }

    // Sinking fund deductions — counted line items on each payday
    const sl=sinkingLog||{};
    for(let d=fromDay;d<=dim;d++){
      const dk=`${year}-${String(month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
      const daySink=sl[dk];
      if(!daySink)continue;
      const labels=[];
      const notes=[];
      let total=0;
      Object.keys(daySink).forEach(pid=>{
        const amt=daySink[pid];
        if(!amt||amt<=0||phaseDone[pid])return;
        const phase=getPhases().find(p=>p.id===pid);
        if(!phase)return;
        labels.push(phase.label);
        const ref=phase.monthlySave?`$${phase.monthlySave}/mo`:phase.percentOfPay?`${phase.percentOfPay}% of pay`:'';
        notes.push(ref+' · '+phase.label);
        total+=amt;
      });
      if(total>0){
        add(d,`→ ${labels.join(', ')} savings`,-total,'#9b82e8',notes.join(' · '),false,true);
      }
    }

    // All bills from getDailyBills (Firebase-driven)
    const todayMidnight = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    for(let d=fromDay; d<=dim; d++) {
      const dCb=cbAsOf(`${year}-${String(month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`);
      getDailyBills(year, month, d, dCb).forEach(b => {
        if (b.isIncome) return; // Already handled above
        // Planned Sunday disc budget: skip past/today — actual disc shown via discLog
        if (!b.billId && b.label === 'Discretionary' && new Date(year, month, d) <= todayMidnight) return;
        const bill = (S.userBills || []).find(x => x.id === b.billId);
        const isDebt = bill && bill.cardId;
        const doneKey = isDebt ? bill.cardId+'-done' : null;
        const debtDone = doneKey && roadmap[doneKey]?.date === `${year}-${String(month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
        const color = debtDone ? '#9b82e8' : isDebt ? '#e8836e' : '#a8a69f';
        const title = debtDone ? b.label+' — CLEARED' : b.label;
        const evtNote = debtDone ? 'Final payment · debt closed' : bill ? (bill.note || '') : '';
        add(d, title, b.amt, color, evtNote, false, debtDone, debtDone, b.billId || null);
      });
    }

    // Expense phase events from roadmap — threshold phases only (sinking shown via sinkingLog)
    getPhases().forEach(phase=>{
      if(phaseDone[phase.id])return;
      if(phase.monthlySave||phase.percentOfPay)return;
      const m=roadmap[phase.id];
      if(!m)return;
      const ed=new Date(m.date+'T12:00:00');
      if(ed.getFullYear()===year&&ed.getMonth()===month){
        const label=phase.isSavings?'TRANSFER → Savings #0725':phase.label.toUpperCase();
        const pCost=phaseAmt(phase.id,phase.cost);
        const note=phase.isSavings?`$${pCost.toLocaleString()} · transfer to savings then tap ✓`:`$${pCost.toLocaleString()} budget · calculated date`;
        add(ed.getDate(),label,-pCost,phase.isSavings?'#9b82e8':'#d4922a',note,false,true);
      }
    });

    // Snowball payment events
    const ssDate=roadmap['snowball-start']?.date;
    if(ssDate){
      const TARGETS = getSnowballTargets();
      for(let dd=fromDay;dd<=dim;dd++){
        const eventDate=`${year}-${String(month+1).padStart(2,'0')}-${String(dd).padStart(2,'0')}`;
        if(eventDate<ssDate)continue;
        // A debt can be fully retired by its own scheduled minimum payment on a day that
        // isn't a payday — surface that CLEARED milestone even when today isn't a payday.
        // On a non-payday the only thing that can zero a card's balance is its own
        // regular bill, so that bill's amount is the real final payment.
        const clearedToday=TARGETS.find(t=>roadmap[t.id+'-done']?.date===eventDate);
        const clearedBillAmt=clearedToday?((S.userBills||[]).find(b=>b.cardId===clearedToday.id)?.amt||0):0;
        const isPayday=dd===7||dd===22||isKarenPayday(year,month,dd);
        if(!isPayday){
          if(clearedToday){
            evts.push({day:dd,title:`${clearedToday.label} — CLEARED`,amt:-clearedBillAmt,color:'var(--pur)',note:'Final minimum payment closes this out',isIncome:false,feat:true,isFinal:true});
          }
          continue;
        }
        const activeTarget=TARGETS.find(t=>{
          if(ssDate>eventDate)return false;
          // Real (unzeroed) balance check: was this already paid off before the
          // simulation even started — not "is it done sometime this month" (that's
          // what the exact-date done.date check right below is for).
          if(bal(S.cardBals||{},t.id)<=0)return false;
          const done=roadmap[t.id+'-done'];
          return!done||done.date>=eventDate;
        });
        // A different (non-active) target can coincidentally clear via its own minimum
        // payment on the same day as a payday — surface it too, without duplicating
        // the active target's own CLEARED event handled below.
        if(clearedToday&&(!activeTarget||clearedToday.id!==activeTarget.id)){
          evts.push({day:dd,title:`${clearedToday.label} — CLEARED`,amt:-clearedBillAmt,color:'var(--pur)',note:'Final minimum payment closes this out',isIncome:false,feat:true,isFinal:true});
        }
        if(!activeTarget)continue;
        const prevDate=new Date(year,month,dd-1).toISOString().split('T')[0];
        const prevBal=balLog[prevDate],todayBal=balLog[eventDate];
        if(prevBal===undefined||todayBal===undefined)continue;
        const dayNet=getDailyBills(year,month,dd,cbAsOf(eventDate)).reduce((a,b)=>a+b.amt,0);
        const rawAmt=Math.round(prevBal+dayNet-todayBal);
        const phaseDeduction=getPhases().filter(p=>{
          const pm=roadmap[p.id];
          return pm&&pm.date===eventDate&&!(phaseDone[p.id])&&!p.monthlySave&&!p.percentOfPay;
        }).reduce((s,p)=>s+phaseAmt(p.id,p.cost),0);
        const sl2=sinkingLog||{};
        const sinkingOnDay=(sl2[eventDate]?Object.values(sl2[eventDate]).reduce((s,a)=>s+a,0):0);
        const payAmt=rawAmt-phaseDeduction-sinkingOnDay;
        if(payAmt<=5)continue;
        const isFinal=roadmap[activeTarget.id+'-done']?.date===eventDate;
        const title=isFinal?`${activeTarget.label} — CLEARED`:`Pay $${Math.round(payAmt).toLocaleString()} → ${activeTarget.label}`;
        evts.push({day:dd,title,amt:-payAmt,color:isFinal?'var(--pur)':'#7aad4e',note:isFinal?'Final payment · debt closed':'Snowball payment · log into card and pay now',isIncome:false,feat:true,isFinal});
      }
    }

    // Logged discretionary spends
    (S.discLog||[]).forEach(e=>{
      if(!e.date||!e.amt)return;
      const sp=new Date(e.date);
      if(isNaN(sp.getTime())||sp.getMonth()!==month||sp.getFullYear()!==year)return;
      const catLabel=e.cat&&e.cat!=='discretionary'?e.cat.charAt(0).toUpperCase()+e.cat.slice(1):'Discretionary';
      const catColor=e.cat==='gas'?'#5c5c58':e.cat==='groceries'?'#4a8fa8':'#6b9fd4';
      add(sp.getDate(),e.label||catLabel,-Math.abs(e.amt),catColor,'Logged · '+catLabel);
    });

    evts.sort((a,b)=>a.day-b.day);
    return evts;
  }

  function toMonthlyAmt(b) {
    if (b.frequency === 'weekly') return b.amt * 4.33;
    if (b.frequency === 'quarterly') return b.amt / 3;
    if (b.frequency === 'biweekly') return (b.amt || 0) * (Array.isArray(b.day) ? b.day.length : 2);
    if (Array.isArray(b.day)) return (b.amt || 0) * b.day.length;
    return b.amt || 0;
  }

  return { getPhases, isoDay, bal, jonPaidThisPeriod, isKarenPayday, getDailyBills, getSnowballTargets, calcRoadmap, getMonthEvents, toMonthlyAmt, phaseAmt, state: S, now };
}
