#!/usr/bin/env python3
"""One-time (re-runnable) extraction of the pure simulation engine out of index.html
into engine.mjs.

Function bodies are copied VERBATIM. Only the enclosing scope changes: the globals the
engine reads (S, now, mKey, DN, MN, DEFAULT_PHASES, DEFAULT_USER_BILLS and the roadmap
memo vars) become closure variables of createEngine(). That keeps behaviour identical
while making the engine callable from Node, a CLI, or a test.

Run:  python3 tools/extract-engine.py  >/dev/null  &&  node --check engine.mjs
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
src = (ROOT / "index.html").read_text()
js = re.search(r'<script type="module">(.*?)</script>', src, re.S).group(1)

def grab_function(name):
    m = re.search(r'(?:^|\n)function\s+' + re.escape(name) + r'\s*\(', js)
    if not m:
        sys.exit(f"extract-engine: function {name} not found")
    i = js.index('{', m.end()); d = 0
    for j in range(i, len(js)):
        if js[j] == '{': d += 1
        elif js[j] == '}':
            d -= 1
            if d == 0:
                return m.start(), js[m.start():j + 1].lstrip('\n')
    sys.exit(f"extract-engine: unbalanced braces in {name}")

def grab_line(pattern):
    m = re.search(pattern, js)
    if not m:
        sys.exit(f"extract-engine: {pattern} not found")
    start = js.rfind('\n', 0, m.start()) + 1
    end = js.index('\n', m.end())
    return start, js[start:end]

PURE = ["getPhases", "isoDay", "bal", "jonPaidThisPeriod", "isKarenPayday",
        "getDailyBills", "getSnowballTargets", "calcRoadmap", "getMonthEvents",
        "toMonthlyAmt"]

pieces = [grab_function(n) for n in PURE]
pieces.append(grab_line(r'const phaseAmt\s*=\s*\('))     # arrow, not a declaration
pieces.sort(key=lambda p: p[0])                           # keep source order
body = "\n\n".join(p[1] for p in pieces)
body = "\n".join(("  " + ln) if ln.strip() else ln for ln in body.split("\n"))

exports = PURE + ["phaseAmt"]

out = '''// GENERATED by tools/extract-engine.py from index.html — do not edit by hand while
// index.html still carries its own copy. Once index.html imports this module, delete
// the generator and maintain this file directly.
//
// The bodies below are byte-identical to the in-page originals. Only the surrounding
// scope changed: the engine's former globals are now closure variables, so the same
// simulation can run in a browser, in Node, from a CLI, or under test.

const SEEDED_PHASES = [
  {id:'repair-buf', label:'Repair buffer (savings)',cost:1000,isSavings:true},
  {id:'jon-tires',  label:"Jon's tires + oil",    cost:1500},
  {id:'karen-tires',label:"Karen's tires",         cost:1000},
  {id:'dental',     label:'Dental — Jon + Karen',  cost:600},
  {id:'glasses',    label:'Glasses — Jon + Karen', cost:1000},
];

export const DEFAULT_PHASES = SEEDED_PHASES;

export const MN = ['January','February','March','April','May','June','July','August','September','October','November','December'];
export const DN = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];

/**
 * @param {object}  opts.state          the Firebase `S` state object
 * @param {Date|string} [opts.now]      "today" for the simulation (default: real now)
 * @param {Array}  [opts.defaultPhases] override the seeded phase list
 */
export function createEngine(opts = {}) {
  const S = opts.state || {};
  const now = opts.now ? new Date(opts.now) : new Date();
  const mKey = `${now.getFullYear()}-${now.getMonth()}`;
  // must be named DEFAULT_PHASES: the verbatim bodies below reference that identifier
  const DEFAULT_PHASES = opts.defaultPhases || SEEDED_PHASES;
  const DEFAULT_USER_BILLS = [];
  let _cachedRoadmap = null, _roadmapCacheKey = '';

__BODY__

  return { __EXPORTS__, state: S, now };
}
'''.replace("__BODY__", body).replace("__EXPORTS__", ", ".join(exports))

(ROOT / "engine.mjs").write_text(out)
print(f"engine.mjs written: {len(out.splitlines())} lines, {len(exports)} exports")
